project:
  type: website
  output-dir: docs

website:
  title: "DiaRio de un TuQmano"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tuqmano
      - icon: twitter
        href: https://twitter.com/tuqmano
format:
  html:
    theme: sketchy
    css: styles.css



