project:
  type: website
  output-dir: docs

website:
  title: "DiaRio de un TuQmano"
  navbar:
    left: 
      - text: 'Opinion'
        href: https://tuqmano.tumblr.com/
      - text: 'Researh'
        href: https://www.researchgate.net/profile/Juan-Ruiz-Nicolini  
      - text: 'r-Universe'
        href:  https://github.com/PoliticaArgentina 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tuqmano
      - icon: twitter
        href: https://twitter.com/tuqmano
format:
  html:
    theme: sketchy
    css: styles.css



